# Generated by Django 5.0 on 2025-11-20 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload medical document (PDF, JPG, PNG)', upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Raw text extracted from document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Document',
                'verbose_name_plural': 'Medical Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(help_text='AI-generated medical summary')),
                ('extracted_entities', models.JSONField(blank=True, default=dict, help_text='Medical entities: symptoms, diagnosis, medications, etc.')),
                ('model_used', models.CharField(default='gemini-pro', help_text='AI model used for generation', max_length=100)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence score (0-1)')),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_text', models.TextField(blank=True, help_text='User-edited version')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='documents.document')),
            ],
            options={
                'verbose_name': 'AI Summary',
                'verbose_name_plural': 'AI Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
